spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es_blog?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379


server:
  port: 8081

