spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es_blog?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

shiro-redis:
  enabled: true
  redis-manager:
    host: 106.52.34.17:6379
    password: 123456


server:
  port: 8081

markerhub:
  jwt:
    secret: 121242454545451545
    expire: 604800
    header: Auhtorization
